app:
  host-url: http://localhost:8080
  test-mail: ${app.test-recipient-email}
  templates-update-cache: 5s
  mail-sending-props:
    core-pool-size: 8
    max-pool-size: 100

spring:
  init:
    mode: never
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  liquibase:
    changeLog: "classpath:db/changelog.sql"
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none
  cache:
    cache-names: users
    caffeine.spec: maximumSize=10000,expireAfterAccess=5m
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${oauth.github.client-id}
            client-secret: ${oauth.github.client-secret}
            scope:
              - email
          google:
            client-id: ${oauth.google.client-id}
            client-secret: ${oauth.google.client-secret}
            scope:
              - email
              - profile
          gitlab:
            client-id: ${oauth.gitlab.client-id}
            client-secret: ${oauth.gitlab.client-secret}
            client-name: GitLab
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: read_user
        provider:
          gitlab:
            authorization-uri: https://gitlab.com/oauth/authorize
            token-uri: https://gitlab.com/oauth/token
            user-info-uri: https://gitlab.com/api/v4/user
            user-name-attribute: email
  sql:
    init:
      mode: always
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: ${mail.username}
    password: ${mail.password}
    port: 587
  thymeleaf.check-template-location: false
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false

logging:
  level:
    root: WARN
    com.javarush.jira: DEBUG
    com.javarush.jira.common.config.MvcConfig: WARN
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

server:
  forward-headers-strategy: framework
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
springdoc.swagger-ui.path: /doc